# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Astandy/schemes/messages.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'Astandy/schemes/messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x41standy/schemes/messages.proto\x12\x0c\x41standy.Base\"9\n\x0b\x42inaryValue\x12\x0e\n\x06isNull\x18\x01 \x01(\x08\x12\r\n\x05\x61rray\x18\x02 \x03(\x0c\x12\x0b\n\x03one\x18\x03 \x01(\x0c\"i\n\tClientMsg\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03\x63ls\x18\x02 \x01(\t\x12\x0c\n\x04\x66unc\x18\x03 \x01(\t\x12\'\n\x04\x64\x61ta\x18\x04 \x03(\x0b\x32\x19.Astandy.Base.BinaryValue\x12\x0c\n\x04\x63ode\x18\x05 \x01(\r\"\x95\x01\n\tException\x12\n\n\x02\x61t\x18\x01 \x01(\x03\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x03\x12;\n\nproperties\x18\x03 \x03(\x0b\x32\'.Astandy.Base.Exception.PropertiesEntry\x1a\x31\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xbc\x01\n\x12\x45xceptionExplained\x12\n\n\x02\x61t\x18\x01 \x01(\x03\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x03\x12\x44\n\nproperties\x18\x03 \x03(\x0b\x32\x30.Astandy.Base.ExceptionExplained.PropertiesEntry\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x1a\x31\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"k\n\x08Response\x12\n\n\x02id\x18\x01 \x01(\t\x12*\n\texception\x18\x02 \x01(\x0b\x32\x17.Astandy.Base.Exception\x12\'\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x19.Astandy.Base.BinaryValue\"a\n\x05\x45vent\x12\x10\n\x08listener\x18\x01 \x01(\t\x12\r\n\x05\x65vent\x18\x02 \x01(\t\x12)\n\x06params\x18\x03 \x01(\x0b\x32\x19.Astandy.Base.BinaryValue\x12\x0c\n\x04\x63ode\x18\x04 \x01(\x03\"C\n\x12\x43ompressedInstance\x12\x19\n\x11uncompressed_size\x18\x01 \x01(\x04\x12\x12\n\ncompressed\x18\x02 \x01(\x0c\"\x9b\x01\n\tServerMsg\x12)\n\tresponses\x18\x01 \x03(\x0b\x32\x16.Astandy.Base.Response\x12#\n\x06\x65vents\x18\x02 \x03(\x0b\x32\x13.Astandy.Base.Event\x12>\n\x14\x63ompressed_instances\x18\x03 \x03(\x0b\x32 .Astandy.Base.CompressedInstanceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Astandy.schemes.messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXCEPTION_PROPERTIESENTRY']._loaded_options = None
  _globals['_EXCEPTION_PROPERTIESENTRY']._serialized_options = b'8\001'
  _globals['_EXCEPTIONEXPLAINED_PROPERTIESENTRY']._loaded_options = None
  _globals['_EXCEPTIONEXPLAINED_PROPERTIESENTRY']._serialized_options = b'8\001'
  _globals['_BINARYVALUE']._serialized_start=48
  _globals['_BINARYVALUE']._serialized_end=105
  _globals['_CLIENTMSG']._serialized_start=107
  _globals['_CLIENTMSG']._serialized_end=212
  _globals['_EXCEPTION']._serialized_start=215
  _globals['_EXCEPTION']._serialized_end=364
  _globals['_EXCEPTION_PROPERTIESENTRY']._serialized_start=315
  _globals['_EXCEPTION_PROPERTIESENTRY']._serialized_end=364
  _globals['_EXCEPTIONEXPLAINED']._serialized_start=367
  _globals['_EXCEPTIONEXPLAINED']._serialized_end=555
  _globals['_EXCEPTIONEXPLAINED_PROPERTIESENTRY']._serialized_start=315
  _globals['_EXCEPTIONEXPLAINED_PROPERTIESENTRY']._serialized_end=364
  _globals['_RESPONSE']._serialized_start=557
  _globals['_RESPONSE']._serialized_end=664
  _globals['_EVENT']._serialized_start=666
  _globals['_EVENT']._serialized_end=763
  _globals['_COMPRESSEDINSTANCE']._serialized_start=765
  _globals['_COMPRESSEDINSTANCE']._serialized_end=832
  _globals['_SERVERMSG']._serialized_start=835
  _globals['_SERVERMSG']._serialized_end=990
# @@protoc_insertion_point(module_scope)
